### PR TITLE
Add support for object layers in Tiled plugin

### PR DESCRIPTION
**Pull request by OttoRobba**
Does what it says on the tin :)

Fully works with layers cached as bitmap but "breaks" when everything is cached (meaning you won't see enemies moving, for example). No idea if I should go ahead with another container or just accept that maybe the person just really wants everything as a bitmap. I'm leaning to the latter.

### CODE REVIEW

**Comment by drhayes** [comment]
Awesome! I was thinking about doing the exact same thing.

Have you thought about how to add collisions? I was thinking they could be a special objectlayer or something which then become a bunch of bodies added to the container... what do you think?

**Comment by OttoRobba** [comment]
Collisions, I believe, would be quite easy.

Add a body and shape to your class, just as you normally would. Be sure to have proper collision groups and callbacks done. Add a call

        game.scene.addObject this

To your class and it will automatically get updated. This should be all you need.

**Comment by drhayes** [comment]
I was more thinking of the platformer/Metroidvania case. For certain layers nearly every tile should be a collision body. Making that many tiny little rectangles seems bloated and weird, though. So maybe you rely on the user to make a specially named object layer called "collisions" or something? Every shape in there becomes a body for collision?

**Comment by OttoRobba** [comment]
Ah yes. For that I'd recommend:

- Having an entity "Platform" that has a body with 0 mass and 0 maxvelocity.
- Create an object layer.
- Draw large object rectangles over the scenary and assign this entity to them. Remember, you can easily pass parameteres like width and height so the entity would be the exact size of the collision box you drew.

**Comment by nvaken** [comment]
First of all, great work! I'm puzzling around a bit with this and found there is a small error in the documentation which suggests that `container` is the third parameter for the object's `init` method while it's actually the fifth.

**Comment by nvaken** [comment]
Another small suggestion: Might it not be better to use the image tile info for the Sprite? Since we're already using the media info for normal tiles. I think the `gid` in the objects JSON refer to the tilesets, by which we could track down the image for the sprite. You might want to pass that to the `init` function so the object can still create it's own Sprite. 

What do you think?

**Comment by ekelokorpi** [comment]
I'm so busy with other things now so don't really have time to take a closer look on your pull requests, but i will keep merging them! (can't merge this one, there are conflicts)

**Pull request closed without merging**
